name: shopping_list
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # localization
  intl: ^0.16.1
  intl_utils: ^1.9.0
  # import from google sheet to arb
  gsheet_to_arb: ^0.1.11
  # helps to implement BLoC pattern
  flutter_bloc: ^6.1.1
  # service locator (DI)
  get_it: ^5.0.1
  # convenient code generator for get_it
  injectable: ^1.0.5
  # annotation for the freezed code generator
  freezed_annotation: ^0.12.0
  # storage
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # shared preferences
  streaming_shared_preferences: ^1.0.1
  # pair / tuble support
  tuple: ^1.0.3
  # firebase
  firebase_core: 0.5.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4
  cloud_firestore: "^0.14.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # convenient code generator for get_it
  injectable_generator: ^1.0.6
  # tool to run code generator
  build_runner: ^1.10.3
  # data / sealed class
  freezed: ^0.12.5
  # generate hive classes
  hive_generator: ^0.8.2


dependency_overrides:
  analyzer: ^0.40.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
        - asset: fonts/JetBrainsMono-Bold.ttf

gsheet_to_arb:
  arb_file_prefix: 'app'
  localization_file_name: 'intl'
  output_directory: 'lib/app/translations/input'
  add_context_prefix: false
  generate_code: false
  gsheet:
    auth_file: "./gsheet_to_arb.yaml"
    category_prefix: "#"
    document_id: "1GSNcfCX7TSn8-TAh05wnl1O_6GF0FSKch-eOjHDaOd0"
    sheet_id: "0"
    columns: # This is an optional setting, if unused will fallback to default values
      key: 0 # The column where the key for the translation is, defaults to 0
      description: 1 # The column where the description is, defaults to 1
      first_language_key: 2 # The first column for the language copy, assumes that all other columns after this one also contains a language translation, defaults to 2
    rows: # This is an optional setting, if unused will fallback to default values
      header_row: 0 # The header row containing the title for each column, such as language codes, defaults to 0
      first_translation_row: 1 # The first row containing translations that should be parsed, assumes that all rows after this one also should be parsed, defaults 1

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: de # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/app/translations/input # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/app/translations/output # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
